### ISSUE TITLE
Random number not getting randomized and all runs are identical

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/cc3d-player5#22] opened 2023-02-15 18:38 UTC
CC3D 4.3.2 (I think 4.3.1 as well)
Windows 11 (I think 10 as well)

CC3D runs are identical as if the random seed is not getting randomized by the system clock or there is an explicit seed hidden somewhere.

Basic CC3D simulation, no explicit import of random module in python, no seed specification in the xml.

**Comment by JulianoGianlupi** [comment] 2023-02-15 19:43
Duplicate of https://github.com/CompuCell3D/CompuCell3D/issues/628, addressed in https://github.com/CompuCell3D/CompuCell3D/pull/629

**Closed by JulianoGianlupi** 2023-02-15 19:43 UTC

**Comment by maciekswat** [comment] 2023-02-15 19:59
Yes there is a bug in those releases. The temporary workaround is to add this to the Potts section
```xml
<RandomNumberGenerator Name="Legacy"/>
```

**Comment by jpsluka** [comment] 2023-02-15 20:21
Adding <RandomNumberGenerator Name="Legacy"/> to the Potts section
freezes the cells in CC3D 4.3.2.

James P. Sluka, PhD
Biocomplexity Institute
Intelligent Systems Engineering
School of Informatics, Computing and Engineering
Indiana University
Bloomington, IN   USA
Office: 812-855-2441
Cell: 317-331-7465

**Comment by maciekswat** [comment] 2023-02-16 01:50
ugh..., well in this case we will need to release new code that fixes the issue with the default random number generator

**Comment by jpsluka** [comment] 2023-02-16 17:50
It also looks like setting an explicit seed in the Potts section doesn’t work.
<RandomSeed>167473</RandomSeed>
<RandomSeed>42</RandomSeed>
Gives the same results.

It also looks like if you use;
import random
random.seed(a=None)
In the python, the CC3D run is the same. But you do get random numbers in the python script.

Any thoughts on how to do multiple runs that are different while waiting for the bug fix? Perhaps if cell field is initialized with BlobInitializer the user could loop over the cells randomly converting to a different cell type? Or delete a small number of randomly chosen cells? (The python random seems to work)

Jim

Give the same simulations
James P. Sluka, PhD
Biocomplexity Institute
Intelligent Systems Engineering
School of Informatics, Computing and Engineering
Indiana University
Bloomington, IN   USA
Office: 812-855-2441
Cell: 317-331-7465
